name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 17
      JAVA_DISTRO: 'temurin'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'Kotlin/kotlin-lsp'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
    
      - name: Build LSP
        run: |
          mkdir -b ./lib
          chmod +x ./scripts/kotlin-lsp.sh
          ./scripts/kotlin-lsp.sh