name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      JAVA_VERSION: 17
      JAVA_DISTRO: 'temurin'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'Kotlin/kotlin-lsp'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
      
      - name: Set up Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
      
      - name: Build Bazel
        working-directory: 'api.core'
        run: |
          touch WORKSPACE
          bazel build //...
    
      - name: Build LSP
        run: |
          cd scripts
          mkdir lib
          chmod +x ./kotlin-lsp.sh
          ./kotlin-lsp.sh